import dgeNft from '../generated/DGENFT.json';
import gemRegistry from '../generated/GemRegistry.json';
import paymentTokenRegistry from '../generated/PaymentTokenRegistry.json';
import reserveManager from '../generated/ReserveManager.json';
import treasury from '../generated/Treasury.json';
import primarySaleAuction from '../generated/PrimarySaleAuction.json';
import marketplace from '../generated/Marketplace.json';
import swapEscrow from '../generated/SwapEscrow.json';
import redemptionManager from '../generated/RedemptionManager.json';
import complianceRegistry from '../generated/ComplianceRegistry.json';

export const dgeNftAbi = dgeNft;
export const gemRegistryAbi = gemRegistry;
export const paymentTokenRegistryAbi = paymentTokenRegistry;
export const reserveManagerAbi = reserveManager;
export const treasuryAbi = treasury;
export const primarySaleAuctionAbi = primarySaleAuction;
export const marketplaceAbi = marketplace;
export const swapEscrowAbi = swapEscrow;
export const redemptionManagerAbi = redemptionManager;
export const complianceRegistryAbi = complianceRegistry;
